### ISSUE TITLE
Next steps to conclude the process - Airtable form is reporting some kind of error

### ISSUE THREAD

**Issue by rommelcarneiro** [Campus-Advisors/campus-advisor-training-rommelcarneiro#12]
Dear @arelia and @ericdrosado, I hope this message finds you well.

I was trying to understand why the campus advisor was not cmopleted and i found two open issues that I thought that was completed. I finished the issues, but when I'm trying to complete the form (https://airtable.com/shr6ZHMoHOb9kBupY), it's not available, just the "Submit" button. When I push it, it shows the following message:

>>>> Looks like this form is empty. Try filling it out before submitting.

Please, let me know what can I do to complete the process.

Best regards, 

Rommel Carneiro

**Comment by arelia** [comment]
Hi @rommelcarneiro!

Great to hear about your interest in becoming a Campus Advisor! The application form is currently closed as the current GitHub Campus Advisors Program is not accepting any new applications at this time. However, the GitHub Campus Advisors Program has quite a few new and engaging revamps and kickoffs coming in the near future, so stay tuned to https://twitter.com/GitHubEducation for the latest news and when applications open up again!

Cheers,
@arelia

**Comment by rommelcarneiro** [comment]
Thank you for the informations, @arelia.
